# refer: https://github.com/YURLAK/YURLAK.github.io
title: Datnd35
author:
  name: Dat Nguyen
  email: datcoder.it@gmail.com
description: “Xin chào! Hi vọng bạn sẽ kiếm được gì hay ho ở đây hihi。”

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: auto
  copyright_time: "2024"
  # generate social links in footer
  social_links:
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/nguyendinhdat/",
      }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - investment.md
  - vue.md
  - communication.md
  - development.md
  - architecture.md
  - leadership.md
  - learning.md
  - senior.md

navbar-links:
  Home: "https://datnd35.github.io"

# Build settings
theme: minima

# Google Analytics
google_analytics: G-SND56RB6P3

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-katex

collections:
  vue:
    output: true
    permalink: /:collection/:path/
  communication:
    output: true
    permalink: /:collection/:path/
  development:
    output: true
    permalink: /:collection/:path/
  architecture:
    output: true
    permalink: /:collection/:path/
  leadership:
    output: true
    permalink: /:collection/:path/
  learning:
    output: true
    permalink: /:collection/:path/
  experiences:
    output: true
  senior:
    output: true
    permalink: /senior/:name
  investment:
    output: true
    permalink: /:collection/:path/

future: true

url: "https://datnd35.github.io"
